Update docker-publish.yml
biomedbigdata/SPONGE-web-backend pull request #10
Opened 2024-09-18 09:48 UTC by Maiykol

2024-09-18 09:51 UTC, lenamariahackl approved these changes
now SPONGE instead of master

2024-09-18 11:06 UTC, LeonHafner requested changes

2024-09-18 11:06 UTC, LeonHafner commented on .github/workflows/docker-publish.yml
> -      # Install the cosign tool except on PR
This part (installation of cosign) can be removed, as we don't use cosign anymore.

2024-09-19 08:02 UTC, LeonHafner approved these changes

2024-09-19 08:06 UTC, merged